version: '2.1'

services:
  mongo-replica:
    container_name: mongo-replica
    build:
      context: ./helpers
      dockerfile: ./mongo-Dockerfile
    volumes:
      - '.:/data/db'
  account-service:
    container_name: account-service
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL='mongodb://mongo-replica:27017,mongo-replica:27018,mongo-replica:27019/banking'
      - NODE_ENV=development
    depends_on:
      mongo-replica:
        condition: service_healthy
    links:
      - mongo-replica
